### ISSUE TITLE
ReviewerIds missing from JobLocale operations 

### ISSUE THREAD

**Issue by Paul7Peterson** [phrase/phrase-js#11]
I've noticed by using the SDK that for the CRUD operations for the `JobLocale` model, there's a parameter that appeares referenced in the [API Documentation](https://developers.phrase.com/api/#post-/projects/-project_id-/jobs/-job_id-/locales) but it's not available in the API of the API methods of the SDK.

This parameter is `reviewer_ids` as `reviewerIds: string`.

**Comment by Paul7Peterson** [comment]
It looks available in the current code (version: `1.3.0`), but this one is not available in NPM (only until version `1.1.0`).

**Comment by theSoenke** [comment]
Hey @Paul7Peterson, we'll try to get out a release as soon as possible including the reviewer ids and I'll post an update here once it's released

**Comment by Paul7Peterson** [comment]
Thank you!

**Comment by sbruhns** [comment]
Hi @Paul7Peterson, sorry for the delay. We released a new version `1.4.0` that supports the current state of our API documentation.

**Comment by Paul7Peterson** [comment]
Thank you so much!
