### ISSUE TITLE
Http Request Error

### ISSUE THREAD

**Issue by alexandretok** [phrase/phrase-js#13]
Hello, I'm having an issue making request. I've tested making the same request with regular angular HttpClient and it works normally, but when I try to make the request with this package it fails and gives me an error with some information.

Version: 1.5.2 (latest available on npm)

HttpClient request:
```
this.http.get(`https://api.phrase.com/v2/projects/${projectId}/locales/en/download?file_format=simple_json`, {
  headers: {
    'authorization': `Bearer ${apiKey}`,
  },
}).subscribe(locale => {
  console.log('LOCALE', locale);
});
```
This request works normally and the locale json is printed.

Using the package to make the same request:
```
    const configuration = new Configuration({
      apiKey: apiKey,
    });

    this.phraseLocalesApi = new LocalesApi(configuration);

    this.phraseLocalesApi.localeDownload({
      projectId: projectId,
      id: 'en',
      fileFormat: 'simple_json',
    }).then(file => {
      console.log('FILE', file);
    }, err => {
      console.log('ERROR', err);
    });
```
When using the package as shown above, I get a 401 response and the following error is printed:
```
{
    "body": {},
    "bodyUsed": false,
    "headers": {},
    "ok": false,
    "redirected": false,
    "status": 401,
    "statusText": "",
    "type": "cors",
    "url": "https://api.phrase.com/v2/projects/********/locales/en/download?file_format=simple_json"
}
```

Am I doing something wrong here?

I've noticed that on the authorization header, there is no `Bearer` prefix before the value. I wonder if that's causing this issue.

Thanks for the help!

**Comment by theSoenke** [comment]
Hi @alexandretok, could you try passing `token ${apiKey}` as the api key? Currently the full value of the authorization header is required by the SDK

**Comment by theSoenke** [comment]
Hi @alexandretok, did this solve the issue? I'll close the issue for now but let me know if there is still any issue
