### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by kp-bogdan-pitaroiu** [phrase/phrase-js#14]
Hello phrase Js library team, I encountered the following issue while trying to fetch the localesList and any related LocalesApi.

So let's see some of the steps that I am doing within my code.

I am using node version 18.15.0

1. Initializing the configurations:
` 
 const token = "token ${process.env.PHRASE-TOKEN}";
 const configuration = new Configuration({
      apiKey: token
    });
`
  
2. Initializing the locales API:
 `this.localesApi = new LocalesApi(configuration);`
 
3. Fetch all localesList
` const list = await this.localesApi.localesList({
      projectId: this.projectId,
    });
`
    
Step 3 is failing with the following error.
`TypeError: Right-hand side of 'instanceof' is not callable`

While looking through the library seems that the error comes from this particular line.
`      var body = (context.body instanceof FormData || context.body instanceof URLSearchParams || isBlob(context.body))
            ? context.body
            : JSON.stringify(context.body);
            `

I have managed to fix the extension by removing the instanceOf part and leaving only context.body

` var body = context.body`

You can find a fix in the following StackOverflow thread: https://stackoverflow.com/questions/43502288/right-hand-side-of-instanceof-is-not-callable

Thanks :)

**Comment by jablan** [comment]
Closing this issue @kp-bogdan-pitaroiu if the above snippet does not solve the issue for you, please reopen. Thanks
