### ISSUE TITLE
Incorrect request body formatting for localeMapping and formatOptions

### ISSUE THREAD

**Issue by unshame** [phrase/phrase-js#16]
Trying to use the UploadsApi uploadCreate method, the localeMapping and formatOptions are incorrectly formatted:

```javascript
const uploadsApi = new UploadsApi(config)

await uploadsApi.uploadCreate({
    projectId: "xxx",
    file,
    fileFormat: "csv",
    localeMapping: { en: 2 },
    formatOptions: {
      key_index: 1,
      comment_index: 3,
      tag_column: 4,
      header_content_row: true,
    },
  })
```

```
locale_mapping [object Object] 
format_options [object Object] 
```

Passing JSON.stringified object ([even though the types specify object](https://github.com/phrase/phrase-js/blob/9c06dab029dac8196e3acd4ec9c879ba63e32e17/src/models/UploadCreateParameters.ts#L92)) the request still fails because the server expectsa different format for the object.

```javascript
const uploadsApi = new UploadsApi(config)

await uploadsApi.uploadCreate({
    projectId: "xxx",
    file,
    fileFormat: "csv",
    localeMapping: JSON.stringify({ en: 2 }),
    formatOptions: JSON.stringify({
      key_index: 1,
      comment_index: 3,
      tag_column: 4,
      header_content_row: true,
    }),
  })
```

Passed:
```
locale_mapping {"en":2}
format_options {"key_index":1,"comment_index":3,"tag_column":4,"header_content_row":true} 
```

Expected by server:
```
locale_mapping[en] 2
format_options[key_index] 1
format_options[comment_index] 3
etc.
```

Same problem is encountered in the online docs: https://developers.phrase.com/api/#post-/projects/-project_id-/uploads
There, in the code samples the request formatting is correct, but the generated requests are incorrectly passing JSON representation of objects.

**Comment by jablan** [comment]
Hey @unshame could you pls give 1.9.1 version a try (with the first variant above)?

**Comment by unshame** [comment]
Sorry, I've already implemented everything I needed with regular fetch, so can't check anymore.
