### ISSUE TITLE
"export 'Configuration' was not found in 'phrase-js'

### ISSUE THREAD

**Issue by Doomkyn** [phrase/phrase-js#17]
Hello.
I'm trying to use the package in Ionic, but when I try to `ionic build --prod`
I get the following error:
```
ERROR in ./src/app/services/language-updater.service.ts 17:46-59
"export 'Configuration' was not found in 'phrase-js'
```

Looks like the thing that breaks up is the import in my service:
`import { Configuration, LocalesApi } from "phrase-js";`

I'm using `"phrase-js": "^1.9.0",` in my package.json
Also tried reinstalling the package, same result.
Also tried with `ionic build --prod --clearCache` after resinstalling the package.

Am I doing something wrong?
Thanks for the help.

**Comment by theSoenke** [comment]
Hi @Doomkyn, the import looks completely valid to me. The only reason I can currently imagine is that some configuration is inferring with the import. I've also just created a new Ionic app and was successfully able to import the `Configuration` class like this
