### ISSUE TITLE
Authorization wia apiKey is not working

### ISSUE THREAD

**Issue by senseiks** [phrase/phrase-js#18]
Hello.
I'm trying to use ProjectsAPI to fetch my projects. I've added configuration like in instruction 
`new Configuration({
    apiKey: token,
    fetchApi: fetch,
  });` 
but getting error 401 - Unautorized when trying to fetch projects.

I'm using "phrase-js": "^1.13.0", in my package.json

Could you check, please?
Thanks in advance.

**Comment by theSoenke** [comment]
Hi @senseiks, could you check that the value passed to `apiKey` starts with `token ` followed by the API key? 
```
apiKey: `token ${TOKEN}`
```

**Comment by senseiks** [comment]
Hi @theSoenke. I've checked with word `token` also, but the result was the same.

**Comment by theSoenke** [comment]
Thanks for checking. To have a more minimalistic example could you also check the token with cURL

```
curl "https://api.phrase.com/v2/projects" -u "<token>:"
```

The colon at the end after the token is important. If this does not return anything you could try creating a new token whether that makes any difference

**Comment by theSoenke** [comment]
And another question. Are you using the US datacenter by any chance?

**Comment by senseiks** [comment]
`curl "https://api.phrase.com/v2/projects" -u "<token>:"` this is working. No, I don't use US datacenter.

**Comment by jablan** [comment]
@senseiks which Node version are you using? Here's a simple example to fetch the locales from a project, that works for me with Node v18 (run using `PHRASE_TOKEN=[your-token-here] npm run start [project-id-here]`):

```js
import { Configuration, LocalesApi } from "phrase-js";
import FormData from "form-data";
import fetch from "node-fetch";

const globalAny = global;
globalAny.window = {
  fetch
}
globalAny.FormData = FormData

const configuration = new Configuration(
  { apiKey: `token ${process.env.PHRASE_TOKEN}` }
)

const localesApi = new LocalesApi(configuration)

let requestParameters = {
  projectId: process.argv[2]
}

localesApi.localesList(requestParameters).then(function (data) { console.log(data) })
```

**Comment by senseiks** [comment]
@jablan I'm using node v20.5.0 in my project. Access token was generated in settings section in profile.

**Comment by jablan** [comment]
@senseiks can you pls paste code that you are using? just replace the tokens/ids before pasting.

**Comment by senseiks** [comment]
I'm using this setup:

`import * as fetch from 'node-fetch';`

`function getConfiguration(token: string) {
  const globalAny: any = global;
  globalAny.FormData = FormData;

  return new Configuration({
    apiKey: <Access Token>,
    fetchApi: fetch,
  });
}`

`async function checkAndCreateProjects(newProjects: string[], token: string) {
  const projectsApi = new ProjectsApi(getConfiguration(token));
  const projects = await projectsApi.projectsList({
    accountId: <Account ID>,
    perPage: 100,
  });
...`

**Comment by jablan** [comment]
`apiKey` field should contain prefix `token ` (e.g: `apiKey: "token MY_TOKEN_HERE"`).

**Comment by senseiks** [comment]
With this config it works! Thank you!
