### ISSUE TITLE
Error running simple project: FormData is not defined

### ISSUE THREAD

**Issue by brunobrossi** [phrase/phrase-js#5]
Hi, 

  I am trying to set up a typescript project with this lib, and when running the example provided on the README.md, I get an error. 

`2020-07-14 17:10:23 ERROR: ReferenceError: FormData is not defined
    at SpacesApi.BaseAPI.createFetchParams (/Users/brunorossi/projects/bull/node_modules/phrase-js/dist/runtime.js:184:45)
    at SpacesApi.<anonymous> (/Users/brunorossi/projects/bull/node_modules/phrase-js/dist/runtime.js:164:35)
    at step (/Users/brunorossi/projects/bull/node_modules/phrase-js/dist/runtime.js:69:23)
    at Object.next (/Users/brunorossi/projects/bull/node_modules/phrase-js/dist/runtime.js:50:53)
    at /Users/brunorossi/projects/bull/node_modules/phrase-js/dist/runtime.js:44:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/brunorossi/projects/bull/node_modules/phrase-js/dist/runtime.js:40:12)
    at SpacesApi.BaseAPI.request (/Users/brunorossi/projects/bull/node_modules/phrase-js/dist/runtime.js:159:16)
    at SpacesApi.<anonymous> (/Users/brunorossi/projects/bull/node_modules/phrase-js/dist/apis/SpacesApi.js:342:51)
    at step (/Users/brunorossi/projects/bull/node_modules/phrase-js/dist/apis/SpacesApi.js:58:23)`

I have tried changing some configs on the `tsconfig.json` but also didn't help.

**Comment by rlisowski** [comment]
Sorry for misleading README. It can work in Node.js env you just need to provide `fetch` and `FormaData` replacement packages eg:

```JSON
{
  "name": "openapi_typescript_test",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
  "scripts": {
    "start": "tsc && node dist/index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/node": "^14.0.1",
    "form-data": "^3.0.0",
    "node-fetch": "^2.6.0",
    "phrase-js": "^1.0.3"
  },
  "devDependencies": {
    "tslint": "^5.20.1",
    "typescript": "^3.9.2"
  }
}
```

and then you can use the API:

```typescript
import {Configuration, SpacesApi} from "phrase-js"
var FormData = require("form-data")
var fetch = require("node-fetch")


const globalAny: any = global;
globalAny.window = {
  fetch
}
globalAny.FormData = FormData

const configuration = new Configuration({apiKey: 'token ACCESS_TOKEN'})

const spaceApi = new SpacesApi(configuration)

let requestParameters = {
  accountId: 'ACCOUNT_ID'
}

spaceApi.spacesList(requestParameters).then(function (data) {console.log(data)})
```

[openapi_typescript_test.zip](https://github.com/phrase/phrase-js/files/4924304/openapi_typescript_test.zip)

**Comment by atellezsazo** [comment]
```
const { Configuration, SpacesApi } = require('phrase-js');

const FormData = require('form-data');
const fetch = require('node-fetch');

const globalAny = global;
globalAny.window = {
  fetch,
};

globalAny.FormData = FormData;

const configuration = new Configuration({
  apiKey:
    'token ACCESS_TOKEN',
});

const spaceApi = new SpacesApi(configuration);

const requestParameters = {
  accountId: 'ACCOUNT_ID',
};

spaceApi
  .spacesList(requestParameters)
  .then(data => {
    console.log(data);
  })
  .catch(e => console.log(e));

```

Trying to make it work on Node JS but it seems like I'm doing something wrong. 

Response:

```
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: true,
      _transformState: [Object],
      [Symbol(kCapture)]: false
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://api.phrase.com/v2/accounts/account-id/spaces',
    status: 400,
    statusText: 'Bad Request',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
```

**Comment by rlisowski** [comment]
You need to replace ACCOUNT_ID with actual account id. You can take it from account details on https://app.phrase.com

**Comment by rlisowski** [comment]
@brunobrossi @atellezsazo is it working for you now? can we close this issue?

**Comment by atellezsazo** [comment]
Yes, it's working perfectly.

**Comment by brunobrossi** [comment]
> @brunobrossi @atellezsazo is it working for you now? can we close this issue?

Hey, yeah! Sorry to get back late, it's working! :) We are starting to use in our project now.

**Comment by rlisowski** [comment]
@brunobrossi just as an alternative path you can grab our [OpenAPI definitions](https://github.com/phrase/openapi) and use different [typescript generator](https://openapi-generator.tech/docs/generators) to build own API client and have 100% control over it.

**Comment by ZainaliSyed** [comment]
> ```json
> e-js": "^1.0
> ```

Thanks alot , It works for me now

**Comment by ZainaliSyed** [comment]
> Sorry for misleading README. It can work in Node.js env you just need to provide `fetch` and `FormaData` replacement packages eg:
> 
> ```json
> {
>   "name": "openapi_typescript_test",
>   "version": "1.0.0",
>   "description": "",
>   "main": "dist/index.js",
>   "scripts": {
>     "start": "tsc && node dist/index.js",
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "@types/node": "^14.0.1",
>     "form-data": "^3.0.0",
>     "node-fetch": "^2.6.0",
>     "phrase-js": "^1.0.3"
>   },
>   "devDependencies": {
>     "tslint": "^5.20.1",
>     "typescript": "^3.9.2"
>   }
> }
> ```
> 
> and then you can use the API:
> 
> ```ts
> import {Configuration, SpacesApi} from "phrase-js"
> var FormData = require("form-data")
> var fetch = require("node-fetch")
> 
> 
> const globalAny: any = global;
> globalAny.window = {
>   fetch
> }
> globalAny.FormData = FormData
> 
> const configuration = new Configuration({apiKey: 'token ACCESS_TOKEN'})
> 
> const spaceApi = new SpacesApi(configuration)
> 
> let requestParameters = {
>   accountId: 'ACCOUNT_ID'
> }
> 
> spaceApi.spacesList(requestParameters).then(function (data) {console.log(data)})
> ```
> 
> [openapi_typescript_test.zip](https://github.com/phrase/phrase-js/files/4924304/openapi_typescript_test.zip)


Thanks alot it works for me
