### ISSUE TITLE
Example of locale download.

### ISSUE THREAD

**Issue by khizar** [phrase/phrase-js#8]
Hi, is my assumption correct that when i use the locale download API, it should download the file in the format provided? Where is the file downloaded file? Here is a snippet i am trying:

```
const projects = await projectsApi.projectsList({});
for (const project of projects) {
  const locales = await localesApi.localesList({ projectId: project.id });
  locales.forEach(async locale => {
    await localesApi.localeDownload({
      projectId: project.id,
      id: locale.id,
      fileFormat: 'yml',
    });
  });
}
```
What i am expecting here is to see each locale file in the folder that this code is run from. Is my assumption wrong? Can you help me clear this up a little if not? Thanks

**Comment by theSoenke** [comment]
Hey @khizar, the content of the translation file should be returned by `await localesApi.localeDownload`. We're not writing files directly to disk as it also can be used in the context of a browser. Let me know if this shouldn't work for you.

**Comment by khizar** [comment]
makes sense, thanks for the response.
